---
- name: restart ssh daemon
  service:
    name: "{{ ssh_daemon }}"
    state: restarted

- name: copy ssh-chroot-jail extra items
  copy:  # noqa 208
    src: "{{ item }}"
    dest: "{{ ssh_chroot_jail_path }}{{ item }}"
    remote_src: true
  with_items: "{{ ssh_chroot_copy_extra_items }}"

- name: add binary libs via l2chroot
  command: "{{ ssh_chroot_l2chroot_path }} {{ item.bin | default(item) }}"
  when: item.l2chroot is not defined or item.l2chroot
  with_items: "{{ ssh_chroot_bins }}"

- name: copy extra libraries for whoami
  shell: "cp {{ lib64_path }}/libns* {{ ssh_chroot_jail_path }}/{{ lib64_path }}/"
  args:
    warn: false
  when: "'/usr/bin/whoami' in ssh_chroot_bins"
